apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-app-deployment
  namespace: flipkart-ns
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flipkart-app
  template:
    metadata:
      labels:
        app: flipkart-app
    spec:
      containers:
        - name: flipkart-app-container
          image: harishnshetty/flipkart:latest # Use your actual Docker image name and tag
          ports:
            - containerPort: 80 # The port your game app is listening on
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-svc
  namespace: flipkart-ns
spec:
  selector:
    app: flipkart-app
  ports:
    - protocol: TCP
      port: 80 # The port exposed by the service within the cluster
      targetPort: 80 # The port your game app is listening on inside the pod
  type: ClusterIP
